apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secrets-owner-binding
subjects:
  - kind: ServiceAccount
    name: first-sa
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: secrets-owner # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
