apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secrets-owner
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["secrets"]
    verbs: ["get", "watch", "list", "create", "delete"]

