apiVersion: apps/v1
kind: Deployment
metadata:
  name: www
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-data
              mountPath: /usr/share/nginx/html/
      initContainers:
        - name: init-nginx
          image: busybox:1.28
          command: ['sh', '-c', 'echo "Hello from Pod: `hostname`!" >> /usr/share/nginx/html/index.html']
          volumeMounts:
            - name: nginx-data
              mountPath: /usr/share/nginx/html/
      volumes:
        - name: nginx-data
          emptyDir: {}
